### PR TITLE
Made images responsive (fluid).

### PR DESCRIPTION
**Pull request by kkomelin**
... and added a couple of examples to the demo.

The approach is similar to Bootstrap's one:
https://github.com/twbs/bootstrap/blob/e38f066d8c203c3e032da0ff23cd2d6098ee2dd6/less/mixins/image.less#L9

```
// Keep images from scaling beyond the width of their parents.
.img-responsive(@display: block) {
  display: @display;
  max-width: 100%; // Part 1: Set a maximum relative to the parent
  height: auto; // Part 2: Scale the height according to the width, otherwise you get stretching
}
```

ref #7

### CODE REVIEW

**Comment by chibisov** [comment]
Could you make example images monochromic? In black and white colours.

**Comment by kkomelin** [comment]
Done. However, I don't really like the quality that Photoshop has given to me.

**Comment by kkomelin** [comment]
It should be better now. Please take a look.

**Comment by chibisov** [comment]
Cool! Thank you!

**Comment by kkomelin** [comment]
Awesome. Thanks.

**Pull request merged**
