### PR TITLE
JS and CSS fixes

### PR DESCRIPTION
**Pull request by kkomelin**
Used location.hash instead location = '#'...
Replaced anchor symbol with its valid HTML alternative.
Fixed responsive navigation bug (issue #1).

### CODE REVIEW

**Comment by chibisov** [comment]
Please, don't forget to run `python compile.py`. It's described in [readme](https://github.com/chibisov/backdoc#development-process)

I'll wait for compiled `backdock.py` in this pull request.

**Comment by kkomelin** [comment]
I've caught the following cross-platform issue when I was trying to compile:

> Traceback (most recent call last):
>   File "compile.py", line 3, in <module>
>     markdown2_src = open('./src/markdown2.py', 'r').read()
>   File "D:\bin\Python34\lib\encodings\cp1251.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 80687: character maps to `<undefined>` 

I use win7 and Python 3.
Did you catch something like this?

**Comment by chibisov** [comment]
No, I don't have such problem. Could you try to add `encoding='utf-8'` to every `open` command in `compile.py`? It'll look like this:

```
# -*- coding: utf-8 -*-
src = open('./src/backdoc.py', 'r', encoding='utf-8').read()
markdown2_src = open('./src/markdown2.py', 'r', encoding='utf-8').read()
template_src = "template_html = u'''{0}'''".format(open('./src/template.html', 'r', encoding='utf-8').read())

compiled_src = (
    src.replace('from markdown2 import Markdown', markdown2_src)
       .replace("template_html = open('./template.html', 'r').read()", template_src)
)

compile_to = open('./backdoc.py', 'w', encoding='utf-8')
compile_to.write(compiled_src)
```

**Comment by kkomelin** [comment]
Thanks, your latest suggestion works fine for me.
Should I also commit compile.py changes?

**Comment by chibisov** [comment]
Yes, add it to pull request.

**Comment by kkomelin** [comment]
Done. Please review and merge.

**Comment by kkomelin** [comment]
Great. Thank you for your assistance Gennady!

**Comment by kkomelin** [comment]
Also, please update the demo branch when you have time.

**Pull request merged**
